from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ScreeningAssessment(BaseModel):
    """
    Fields that must be generated by the LLM.

    The total score and recommendation are deliberately excluded because the
    application calculates them locally.
    """

    model_config = ConfigDict(extra="forbid")

    required_skills_score: int = Field(ge=0, le=30)
    preferred_skills_score: int = Field(ge=0, le=10)
    experience_score: int = Field(ge=0, le=25)
    education_score: int = Field(ge=0, le=15)
    project_relevance_score: int = Field(ge=0, le=20)

    matched_skills: list[str] = Field(default_factory=list)
    missing_required_skills: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    justification: str = ""


class ScreeningResult(ScreeningAssessment):
    """Final validated result returned by the application."""

    total_score: int = Field(ge=0, le=100)

    recommendation: Literal[
        "Strong Match",
        "Potential Match",
        "Not Recommended"
    ]


def build_screening_result(assessment: ScreeningAssessment) -> ScreeningResult:
    total_score = (
        assessment.required_skills_score
        + assessment.preferred_skills_score
        + assessment.experience_score
        + assessment.education_score
        + assessment.project_relevance_score
    )

    if total_score >= 80:
        recommendation = "Strong Match"
    elif total_score >= 60:
        recommendation = "Potential Match"
    else:
        recommendation = "Not Recommended"

    return ScreeningResult(
        **assessment.model_dump(),
        total_score=total_score,
        recommendation=recommendation,
    )
